In [2]:
import numpy as np

Ar1 = np.array([2, 4, 6, 8, 10])

print(Ar1)


[ 2  4  6  8 10]


In [3]:
Ar2 = np.zeros([3,3])
print (Ar2)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
Ar3 = np.ones([4,4])
print(Ar3)




[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
Ar4 = np.arange(1,21,2)
print(Ar4)


[ 1  3  5  7  9 11 13 15 17 19]


In [16]:
Ar5 = np.linspace(0,1,11)
print(Ar5)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [17]:
Ar6 = np.eye(4)
print(Ar6)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
Ar7 = np.array([1,2,3,4,5])

print(Ar7.shape)
print(Ar7.size)
print(Ar7.dtype)

(5,)
5
int64


In [24]:
Ar8 = np.arange(1,13)
print(Ar8)

NewAr8 = Ar8.reshape(3,4)
print(NewAr8)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
Ar9 = np.array([[1,2] , [3,4] , [5,6]])
print(Ar9)

New_Ar9 = Ar9.ravel()
print(New_Ar9)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [29]:
A = np.array([1,2,3])
B = np.array([4,5,6])

print(A + B)

[5 7 9]


In [34]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([1,1,1])

c = a + b
print(c)



[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [35]:
int_arr = np.array([1,2,3])
float_arr = np.array([0.5 , 1.5 , 2.5])

New_arr = int_arr + float_arr
print(New_arr)
print(New_arr.dtype)


[1.5 3.5 5.5]
float64


In [37]:
Ar10 = np.array([2, 6, 8, 3, 1, 9])

print(Ar10[Ar10 > 5])

[6 8 9]


In [43]:
Ar11 = np.arange(10,21)

New = Ar11[2:7]
print(New)

[12 13 14 15 16]


In [45]:
Arr = np.arange(1,25)
New_Arr = Arr.reshape(2,3,4)
print(New_Arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [49]:
Arr = np.random.randint(10 , 50 , 25)
New_Arr = Arr.reshape(5,5)
print(New_Arr)

Even_numbers = New_Arr[New_Arr % 2 == 0]
print(Even_numbers)

[[15 31 38 23 21]
 [42 10 16 18 14]
 [25 33 43 45 28]
 [32 41 46 23 20]
 [47 43 18 20 42]]
[38 42 10 16 18 14 28 32 46 20 18 20 42]


In [54]:
a = np.arange(1,13).reshape(3,4)
b = np.array([10,20,30,40])

c = a + b

print("Array a:\n" , a)

print("Array b:\n" , b)

print("Array c:\n" , c)


Array a:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array b:
 [10 20 30 40]
Array c:
 [[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]
